spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/paymentdb
aws:
  sqs:
    partialPaymentQueueUrl: https://sqs.sa-east-1.amazonaws.com/442426883417/ScrSanGiorgioQueue.fifo
    fullPaymentQueueUrl: https://sqs.sa-east-1.amazonaws.com/442426883417/ScrSanGiorgioQueue.fifo
    excessPaymentQueueUrl: https://sqs.sa-east-1.amazonaws.com/442426883417/ScrSanGiorgioQueue.fifo