spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/paymentdb
aws:
  sqs:
    partialPaymentQueueUrl: # real url
    fullPaymentQueueUrl: # real url
    excessPaymentQueueUrl: # real url